services:
  FA3ST:
    image: fraunhoferiosb/faaast-service
    container_name: FA3ST
    volumes:
      - ./resources/model.aasx:/app/resources/model.aasx
      - ./resources/config.json:/app/resources/config.json
    environment:
      - faaast_model=/app/resources/model.aasx
      - faaast_config=/app/resources/config.json
    ports:
      - 8081:8081
    restart: always

  integration:
    build: ./integration
    environment:
      MQTT_BROKER: 131.255.82.115
      MQTT_PORT: 1883
      MQTT_TOPIC: esp32/17/monitor/cmd
      CLIENT_ID: esp32
    command: python integration.py
    restart: always

